import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Dropdown } from "./dropdown/dropdown";
import { Canvas } from "./canvas/canvas";
import { AppProvider } from "./context/AppContext";
import { ColorPanel } from "@/app/canvas/color-panel/color-panel";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <Dropdown />
          <div style={{ display: "grid", placeItems: "center" }}>
            <Canvas />
          </div>
          <ColorPanel />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
