// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pixel.proto

package pixelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PixelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Color         uint32                 `protobuf:"varint,4,opt,name=color,proto3" json:"color,omitempty"`
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixelInfo) Reset() {
	*x = PixelInfo{}
	mi := &file_pixel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixelInfo) ProtoMessage() {}

func (x *PixelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pixel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixelInfo.ProtoReflect.Descriptor instead.
func (*PixelInfo) Descriptor() ([]byte, []int) {
	return file_pixel_proto_rawDescGZIP(), []int{0}
}

func (x *PixelInfo) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PixelInfo) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PixelInfo) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *PixelInfo) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PixelInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_pixel_proto protoreflect.FileDescriptor

const file_pixel_proto_rawDesc = "" +
	"\n" +
	"\vpixel.proto\x12\x05pixel\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\tPixelInfo\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05color\x18\x04 \x01(\rR\x05color\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\vZ\t./pixelpbb\x06proto3"

var (
	file_pixel_proto_rawDescOnce sync.Once
	file_pixel_proto_rawDescData []byte
)

func file_pixel_proto_rawDescGZIP() []byte {
	file_pixel_proto_rawDescOnce.Do(func() {
		file_pixel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pixel_proto_rawDesc), len(file_pixel_proto_rawDesc)))
	})
	return file_pixel_proto_rawDescData
}

var file_pixel_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pixel_proto_goTypes = []any{
	(*PixelInfo)(nil),             // 0: pixel.PixelInfo
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pixel_proto_depIdxs = []int32{
	1, // 0: pixel.PixelInfo.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pixel_proto_init() }
func file_pixel_proto_init() {
	if File_pixel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pixel_proto_rawDesc), len(file_pixel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pixel_proto_goTypes,
		DependencyIndexes: file_pixel_proto_depIdxs,
		MessageInfos:      file_pixel_proto_msgTypes,
	}.Build()
	File_pixel_proto = out.File
	file_pixel_proto_goTypes = nil
	file_pixel_proto_depIdxs = nil
}
