// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: message.proto

package proxy_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_DRAW      Command = 0
	Command_PROCESSED Command = 1
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "DRAW",
		1: "PROCESSED",
	}
	Command_value = map[string]int32{
		"DRAW":      0,
		"PROCESSED": 1,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type AirplaceBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       Command                `protobuf:"varint,1,opt,name=command,proto3,enum=proxy.Command" json:"command,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Color         uint32                 `protobuf:"varint,4,opt,name=color,proto3" json:"color,omitempty"`
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirplaceBody) Reset() {
	*x = AirplaceBody{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirplaceBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirplaceBody) ProtoMessage() {}

func (x *AirplaceBody) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirplaceBody.ProtoReflect.Descriptor instead.
func (*AirplaceBody) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *AirplaceBody) GetCommand() Command {
	if x != nil {
		return x.Command
	}
	return Command_DRAW
}

func (x *AirplaceBody) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AirplaceBody) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AirplaceBody) GetColor() uint32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *AirplaceBody) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AirplaceBody) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x05proxy\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n" +
	"\fAirplaceBody\x12(\n" +
	"\acommand\x18\x01 \x01(\x0e2\x0e.proxy.CommandR\acommand\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x14\n" +
	"\x05color\x18\x04 \x01(\rR\x05color\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*\"\n" +
	"\aCommand\x12\b\n" +
	"\x04DRAW\x10\x00\x12\r\n" +
	"\tPROCESSED\x10\x01B\fZ\n" +
	"./proxy-pbb\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_message_proto_goTypes = []any{
	(Command)(0),                  // 0: proxy.Command
	(*AirplaceBody)(nil),          // 1: proxy.AirplaceBody
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_message_proto_depIdxs = []int32{
	0, // 0: proxy.AirplaceBody.command:type_name -> proxy.Command
	2, // 1: proxy.AirplaceBody.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
